export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Margherita',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'food1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Chicken MeatBalls',
    cookTime: '20-30',
    price: 20,
    favorite: true,
    origins: ['persia', 'middle-east', 'china'],
    stars: 5,
    imageUrl: 'food2.jpg',
    tags: ['Slowfood', 'Lunch'],
  },
  {
    id: '3',
    name: 'Chicken Biryani',
    cookTime: '10-15',
    price: 10,
    favorite: false,
    origins: ['India', 'Dubai'],
    stars: 3.5,
    imageUrl: 'food3.jpg',
    tags: ['Biryani','Lunch'],
  },
  {
    id: '4',
    name: 'French Fries',
    cookTime: '15-20',
    price: 2,
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3,
    imageUrl: 'food4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'Chicken soup',
    cookTime: '40-50',
    price: 11,
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.5,
    imageUrl: 'food5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'Vegatables Pizza',
    cookTime: '40-50',
    price: 9,
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'food6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags=[
  {name: 'All',count:6},
  {name:'FastFood',count:3},
  {name:'Pizza' ,count:2},
  {name:'Lunch',count:4},
  {name:'SlowFood',count:1},
  {name:'Biryani',count:1},
  {name:'Fry',count:1},
  {name:'Soup',count:1},
];